apiVersion: v1
data:
  .dockerconfigjson: some-base-64-shit
kind: Secret
metadata:
  creationTimestamp: "2022-12-14T09:07:39Z"
  name: demoapp-regcred
  namespace: default
  resourceVersion: "505031"
  uid: b8de300e-a569-47cf-9d96-56d4f3296043
type: kubernetes.io/dockerconfigjson
