apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5hcHAuaXRlb3Muc2Nod2FyeiI6eyJ1c2VybmFtZSI6Ims4c19jbHVzdGVyX3ByaW5jaXBsZXMiLCJwYXNzd29yZCI6ImdscGF0LUFFUnM1S0ZGamZKa3N6YmFWaDV6IiwiZW1haWwiOiJNdWhhbW1hZC5TYXJpbV9aYWZhckBtYWlsLnNjaHdhcnoiLCJhdXRoIjoiYXpoelgyTnNkWE4wWlhKZmNISnBibU5wY0d4bGN6cG5iSEJoZEMxQlJWSnpOVXRHUm1wbVNtdHplbUpoVm1nMWVnPT0ifX19
kind: Secret
metadata:
  creationTimestamp: "2022-12-14T09:07:39Z"
  name: demoapp-regcred
  namespace: default
  resourceVersion: "505031"
  uid: b8de300e-a569-47cf-9d96-56d4f3296043
type: kubernetes.io/dockerconfigjson
