apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: onedirection-app
  namespace: default
spec:
  dnsNames:
    - demo.msarimz.eu
  secretName: letsencrypt-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer