apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-app
  namespace: default
spec:
  dnsNames:
    - demo.msarimz.eu
  secretName: tls-demo-app
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer